#!/usr/bin/env bash


BASE_DIR="/usr/local/eminfo/"
if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
        source ${BASE_DIR}/bin/include 2>&-
else
        echo -en "{unknown}:{str}:{include file not exists or empty}"
	exit 3
fi

# Return Codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_NOOP=4

# Set Default
EXIT_STATUS=0
LEVEL=        ### { ok | warn | crit | unknown | noop }
TYPE=         ### { str| file }
CONTENT=      ### { strings | /path/to/result.file }

# Read plugin config value here
sample_email_file=$( read_eminfo_config remote_mailtest sample_email_file )
mail_body_file=$( read_eminfo_config remote_mailtest mail_body_file )
helo_greeting_fqdn=$( read_eminfo_config remote_mailtest helo_greeting_fqdn )

# if null or invalid set default.
[ -z "${helo_greeting_fqdn}" ] && helo_greeting_fqdn="eyou.net."

# if null return STATE_UNKNOWN


# check function here.
check() {
  local total=0  errnum=0  result=  base_domain=  ### {object number} {faile number} {return information}

  [ -f "/usr/bin/host" -a -x "/usr/bin/host" ] || {
        EXIT_STATUS=${STATE_UNKNOWN};
        LEVEL="unknown";
        TYPE="str";
        CONTENT="Util: [/usr/bin/host] not prepared.";
        return
  }

  if [ -z "${sample_email_file}" ]; then
	EXIT_STATUS=${STATE_UNKNOWN}
        LEVEL="unknown"
        TYPE="str"
        CONTENT="sample_email_file not set."
	return
  fi

  if [ -f "/${sample_email_file##*file:}" -a -s "/${sample_email_file##*file:}" ]; then
	sample_email_file="/${sample_email_file##*file:}"
  elif [ -f "${BASE_DIR}/${sample_email_file##*file:}" -a -s "${BASE_DIR}/${sample_email_file##*file:}" ]; then
	sample_email_file="${BASE_DIR}/${sample_email_file##*file:}"
  else
	EXIT_STATUS=${STATE_UNKNOWN}
	LEVEL="unknown"
	TYPE="str"
	CONTENT="sample_email_file [${sample_email_file}] not exist or empty"
	return
  fi

  if [ -z "${mail_body_file}" ]; then
        EXIT_STATUS=${STATE_UNKNOWN}
        LEVEL="unknown"
        TYPE="str"
        CONTENT="mail_body_file not set."
	return
  fi

  if [ -f "/${mail_body_file##*file:}" -a -s "/${mail_body_file##*file:}" ]; then
	mail_body_file="/${mail_body_file##*file:}"
  elif [ -f "${BASE_DIR}/${mail_body_file##*file:}" -a -s "${BASE_DIR}/${mail_body_file##*file:}" ]; then
	mail_body_file="${BASE_DIR}/${mail_body_file##*file:}"
  else
	EXIT_STATUS=${STATE_UNKNOWN}
	LEVEL="unknown"
	TYPE="str"
	CONTENT="mail_body_file [${mail_body_file}] not exist or empty"
	return
  fi

  local v4_config="/var/eyou/etc/eyou_smtpd_config"
  local v5_config="/usr/local/eyou/mail/etc/eyou_mail.ini"
  if [ -f "${v5_config}" -a -s "${v5_config}" ]; then
	base_domain=$(awk -F"=" '($1~/server_me\>/) {$1="";print;exit;}' "${v5_config}" 2>&- | tr -d '[" \t\n]' )
  elif [ -f "${v4_config}" -a -s "${v4_config}" ]; then
	base_domain=$(awk '($1~/o_value\>/) {$1="";print;exit;}' "${v4_config}" 2>&- | tr -d '[" \t\n]' )
  fi
  [ -z "${base_domain}" ] && base_domain="demo.eyou.net"

  local content=$( awk -F":::" '($0!~/^[ \t]*$/ && $0!~/^[ \t]*#/)' "${sample_email_file}" 2>&- )
  local remote_domain=$( echo -e "${content}" | awk -F":::" '{print $1}' )
  for x in `echo "${remote_domain}"`
  do
	local str1=  str2=  subject="Remote Test Mail from [${base_domain}] at $(date +%F_%T)"
	### first set mx-host if specified.
	local mx_host=$( echo -e "${content}" | awk -F ":::" '($1~/'${x}'\>/) {print $2;exit;}' | tr -d '[ \t]' )
	if [ -z "${mx_host}" ]; then
		### search best mx-host for domain: ${x/#@/} if not specified.
		local mx_host=$( /usr/bin/host -t mx ${x/#@/} 2>&- | awk '($(NF-1)~/[0-9]+/ && $0~/'${x/#@/}'/) {print $(NF-1),$NF}' | sort -n | awk '{print $NF;exit}' )
	fi
	if [ -z "${mx_host}" ]; then
		result=" ${str} $( html_red "Sorrsy: can NOT get mx for domain: [${x/#@/}]. SKIP" ) ### ### "
		((total++))
		((errnum++))
		continue
	fi

	xlist=$( echo -e "${content}" | awk -F ":::" '($1~/'${x}'\>/) {$1=$2="";print;exit;}' )
	for y in `echo "${xlist}"`
	do
		str1=$( ${SENDEMAIL} -f "eminfo@${base_domain}" -t "${y}" -s "${mx_host}" -u "${subject}" -o message-file="${mail_body_file}"  -o fqdn="${helo_greeting_fqdn}" -o message-charset=utf8 2>&1 )
		rc=$?
  		str2=$( echo -e "${str1}" | awk -F "sendEmail" '{$1="";print}' | awk -F: '{for(x=2;x<=NF;x++) {printf $x}}')
		if [ "${rc}" == "0" ]; then
			result=" $result remote mail to [${y}] return [${str2}] ### "
			result=" $result talked with mx-host: [${mx_host}] ### "
			result=" $result subject: [${subject}] ### ### "
		else
			result=" $result $(html_red "remote mail to [${y}] return [${str1}]") ### "
			result=" $result talked with mx-host: [${mx_host}] ### "
			result=" $result subject: [${subject}] ### ###"
			((errnum++))
		fi
		((total++))
	done
  done

  if [ "${errnum}" == "0" ]; then
        EXIT_STATUS=${STATE_OK};
        LEVEL="ok";
        TYPE="str";
        CONTENT="Remote Mail Test OK | ${total}/${total} remote mail test succeed | "${result}" "
  else
        EXIT_STATUS=${STATE_CRITICAL};
        LEVEL="crit";
        TYPE="str";
        CONTENT="Remote Mail Test CRITICAL | ${errnum}/${total} remote mail test failed | "${result}" "
  fi
}

check

# output result and return exit status here.
echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
exit ${EXIT_STATUS}
