#!/usr/bin/env bash


BASE_DIR="/usr/local/eminfo/"
if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
        source ${BASE_DIR}/bin/include 2>&-
else
        echo -en "{unknown}:{str}:{include file not exists or empty}"
	exit 3
fi

show_help(){
cat <<EOF
Arguments:   {d|data|h|help}  {fs|io|space|inode}  {ext3 ext4 ...}

Usage:	 data  fs|io|space|inode  "ext3 ext4"

Output:   
FS_Stat: {device} {fstype} {stat}
Disk_IO: {device} {fstype} {success|warn} {io-result}
Disk_Space: {device} {fstype} {mount_point} {free_spcace}M {free_space_pct}%
Inode_Space: {device} {fstype} {mount_point} {free_inode_pct}%

FS_Stat: /dev/mapper/VolGroup-lv_root ext4 clean
FS_Stat: /dev/sda1 ext4 clean
Disk_IO: / ext4 success
Disk_IO: /boot ext4 success
Disk_Space: /dev/mapper/VolGroup-lv_root ext4 / 2949M 45%
Inode_Space: /dev/mapper/VolGroup-lv_root ext4 / 69%
EOF
exit 0;
}
MODE=0
[ "$1" == "data" -o "$1" == "d" ] && MODE=1
[ "$1" == "help" -o "$1" == "h" ] && show_help;


# Return Codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_NOOP=4

# Set Default
EXIT_STATUS=0
LEVEL=    	### { ok | warn | crit | unknown | noop }
TYPE=   	### { str| file }
CONTENT=        ### { strings | /path/to/result.file }

# Read plugin config value here
if [ "${MODE}" == "1" ]; then
	action="$2"
	filesystem_fstype="$3"
else
	filesystem_fstype=$( read_eminfo_config disk_fs filesystem_fstype )
	exclude_mpoint=$( read_eminfo_config disk_fs exclude_mpoint )
	disk_spare_space_uplimit=$( read_eminfo_config disk_fs disk_spare_space_uplimit )
	disk_spare_percent_uplimit=$( read_eminfo_config disk_fs disk_spare_percent_uplimit )
	inode_spare_percent_uplimit=$( read_eminfo_config disk_fs inode_spare_percent_uplimit )
fi

# if null return STATE_UNKNOWN.

# if null or invalid set default.
[ -z "${filesystem_fstype//[ ]}" ] && filesystem_fstype="ext3 ext4"
[ -z "${exclude_mpoint//[ ]}" ] && exclude_mpoint="/dev/shm /dev /boot /sys /proc"
[ -z "${disk_spare_space_uplimit}" -o ! -z "${disk_spare_space_uplimit//[0-9]}" ] && disk_spare_space_uplimit=10000
[ -z "${disk_spare_percent_uplimit}" -o ! -z "${disk_spare_percent_uplimit//[0-9]}" ] && disk_spare_percent_uplimit=10
[ -z "${inode_spare_percent_uplimit}" -o ! -z "${inode_spare_percent_uplimit//[0-9]}" ] && inode_spare_percent_uplimit=10


# check function here
check(){

  [ -f "/bin/df" -a -x "/bin/df" -a -f "/sbin/tune2fs" -a -x "/sbin/tune2fs" ] || {
        EXIT_STATUS=${STATE_UNKNOWN};
        LEVEL="unknown";
        TYPE="str";
        CONTENT="Command: [/bin/df] or [/sbin/tune2fs] not prepared.";
        return
  }

  [ -f "/etc/mtab" -a -s "/etc/mtab" ] || {
	EXIT_STATUS=${STATE_UNKNOWN};
	LEVEL="unknown";
	TYPE="str";
	CONTENT="File: [/etc/mtab] not prepared.";
	return
  }

  local result= mpoint= warnnum=0

  result="$(html_green "Check FileSystem Stat on [${filesystem_fstype}]") ### ###"
  for t in `echo "${filesystem_fstype}"`
  do
	devices=$(awk '($3~/\<'${t}'\>/){print $1}' "/etc/mtab" 2>&-|tr '\n' ' ')
  	for d in `echo "${devices}"`
  	do
		stat=$(/sbin/tune2fs -l "${d}" | awk -F: '($1~/Filesystem state/){gsub(" ","",$2);print $2;exit}')
		# output data and exit if MODE=1
		[ "${MODE}" == "1" -a "${action}" == "fs" ] && {
			echo "FS_Stat: ${d} ${t} ${stat}"
			continue
		}
		if [ "${stat}" == "clean" ]; then
			result="${result} (${t}) ${d} -> ${stat} ###"
		else
			((warnnum++))
			result="${result} $(html_red "(${t}) ${d} -> ${stat}") ###"
		fi
  	done
  done

  result="${result} ### ### $(html_green "Check IO R/W on [${filesystem_fstype}]") ### ###"
  for t in `echo "${filesystem_fstype}"`
  do  
        mpoint=$(awk '($3~/\<'${t}'\>/){print $2}' "/etc/mtab" 2>&-|tr '\n' ' ')
        for m in `echo "${mpoint}"`
        do  
                ioerr=$(/bin/touch "${m}/.disk_fs.iotest" 2>&1 1>/dev/null)
  		rc=$?
                # output data and exit if MODE=1
                [ "${MODE}" == "1" -a "${action}" == "io" ] && {
			if [ "${rc}" == "0" ]; then
                        	echo "Disk_IO: ${m} ${t} success"
			else
				((warnnum++))
				echo "Disk_IO: ${m} ${t} warn \"${ioerr}\""
			fi
                        continue
                }   
                if [ "${rc}" == "0" ]; then
                        result="${result} (${t}) ${m} -> IO R/W Success ### "
                else
                        result="${result} $(html_red "(${t}) ${m} -> IO R/W Warning: ${ioerr}") ### "
                fi  
        done
  done

  result="${result} ### ### $(html_green "Space Check") ### ### "
  for t in `echo "${filesystem_fstype}"`
  do
	mpoint=$(awk '($3~/\<'${t}'\>/){print $1}' "/etc/mtab" 2>&-|tr '\n' ' ')
	for m in `echo "${mpoint}"`
	do
		line=( $(/bin/df -P -T -m "${m}" 2>&- | tail -n +2) )
		if [ "${#line[@]}" != "7" ]; then
			((warnnum++))
			result="${result} $(html_red "filed number [${#line[@]}] <> 7") ###"
			continue
		fi
		if [ "${line[5]//[0-9]}" != "%" ]; then
			((warnnum++))
			result="${result} $(html_red "percent filed [${line[5]}] unrecognized") ###"
			continue
		fi
		if [ "$(echo -e "${exclude_mpoint}"|grep -E -o -w "${line[6]}")" != "" ]; then
			result="${result} ["${line[@]}"] SKIP. as mount point=[${line[6]}] ###"
			continue
		fi

		local device="${line[0]}"  fstype="${line[1]}"  mount="${line[6]}"
		local spare_space="${line[4]}"  spare_pct=$((100-$(echo "${line[5]}"|tr -d '%')))

		# output data and exit if MODE=1
		if [ "${MODE}" == "1" -a "${action}" == "space" ]; then
			echo "Disk_Space: ${device} ${fstype} ${mount} ${spare_space}M ${spare_pct}%"
			continue
		fi

		# check spare space
		if [ "$(echo "${spare_space}<=${disk_spare_space_uplimit}" | bc 2>&-)" == "1" ]; then
			((warnnum++))
			result="${result} $(html_red "${device} -> ${mount} (${fstype}) : spare [${spare_space}M] <= [${disk_spare_space_uplimit}M]") ###"
		else
			result="${result} ${device} -> ${mount} (${fstype}) : spare [${spare_space}M] ###"
		fi

		# check spare space percent
		if [ "$( echo "${spare_pct}<=${disk_spare_percent_uplimit}" | bc 2>&- )" == "1" ]; then
			((warnnum++))
			result="${result} $(html_red "${device} -> ${mount} (${fstype}) : spare [${spare_pct}%] <= [${disk_spare_percent_uplimit}%]") ### "
		else
			result="${result} ${device} -> ${mount} (${fstype}) : spare [${spare_pct}%] ###"
		fi
	done
  done

  result="${result} ### ### $(html_green "Inode Check") ### ### "
  for t in `echo "${filesystem_fstype}"`
  do
	mpoint=$(awk '($3~/\<'${t}'\>/){print $1}' "/etc/mtab" 2>&-|tr '\n' ' ')
	for m in `echo "${mpoint}"`
	do
		line=( $(/bin/df -P -T -i "${m}" 2>&- | tail -n +2) )
		if [ "${#line[@]}" != "7" ]; then
			((warnnum++))
			result="${result} $(html_red "filed number [${#line[@]}] <> 7") ###"
			continue
		fi
		if [ "${line[5]//[0-9]}" != "%" ]; then
			((warnnum++))
			result="${result} $(html_red "percent filed [${line[5]}] unrecognized") ###"
			continue
		fi
		if [ "$(echo -e "${exclude_mpoint}"|grep -E -o -w "${line[6]}")" != "" ]; then
			result="${result} ["${line[@]}"] SKIP. as mount point=[${line[6]}] ###"
			continue
		fi

		local device="${line[0]}"  fstype="${line[1]}"  mount="${line[6]}"
		local spare_pct=$((100-$(echo "${line[5]}" | tr -d '%')))

        	# output data and exit if MODE=1
        	if [ "${MODE}" == "1" -a "${action}" == "inode" ]; then
                	echo "Inode_Space: ${device} ${fstype} ${mount} ${spare_pct}%"
                	continue
         	fi  

		# check inode spare percent
		if [ "$(echo "${spare_pct}<=${inode_spare_percent_uplimit}" | bc 2>&-)" == "1" ]; then
			((warnnum++))
			result="${result} $(html_red "${device} -> ${mount} (${fstype}) : spare [${spare_pct}%] <= [${inode_spare_percent_uplimit}%]") ###"
		else
			result="${result} ${device} -> ${mount} (${fstype}) : spare [${spare_pct}%] ###"
		fi
	done
  done

  # exit if MODE=1
  [ "${MODE}" == "1" ] && exit;

  [ "${warnnum}" -gt "0" ] && {
	EXIT_STATUS=${STATE_WARNING};
	LEVEL="warn";
	TYPE="str";
	CONTENT="Check Disk Spare WARNING | ${warnnum} check failed.| ${result} "
  } || {
	EXIT_STATUS="${STATE_OK}"
	LEVEL="ok"
	TYPE="str"
	CONTENT="Check Disk Spare OK | fsstat,iorw,space,inode check success. | ${result} "
  }

}

check

# output result and return exit status here.
echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
exit ${EXIT_STATUS}
