#!/usr/bin/env perl
use strict;
use warnings;
use Net::POP3;
use Time::HiRes;
use Benchmark ':hireswallclock';

# return codes
our ($state_ok,$state_warn,$state_crit,$state_unkn,$state_noop) = (0,1,2,3,4);

# return stuff
our ($rc, $result) = (0,'');

our $filename = (split /\//, __FILE__)[-1];

# read plugin config here
our $addr_port = `eminfo v $filename addr_port`;
if ($? != 0) {
  $addr_port = '127.0.0.1:110';
} else {
  chomp $addr_port;
}

our $time_out = `eminfo v $filename time_out`
if ($? != 0) {
  $time_out = 5;
} else {
  chomp $time_out;
  $time_out = 5 unless $time_out;
  $time_out = 5 if $time_out ~ /\D/;
}

our $pop_user = `eminfo v $filename pop_user`;
if ($? != 0) {
  $pop_user = '';
} else {
  chomp $pop_user;
}

our $pop_pass = `eminfo v $filename pop_pass`;
if ($? != 0) {
  $pop_pass = '';
} else {
  chomp $pop_pass;
}

